## Chromosome information
chromosome_defaults:
  hg19:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - X

  hg38:
    - chr1
    - chr2
    - chr3
    - chr4
    - chr5
    - chr6
    - chr7
    - chr8
    - chr9
    - chr10
    - chr11
    - chr12
    - chr13
    - chr14
    - chr15
    - chr16
    - chr17
    - chr18
    - chr19
    - chr20
    - chr21
    - chr22
    - chrX

## resource params
mem_per_cpu: 7900

# Blank if want to use only automated purity/ploidy
models:
    COLO829-TestA:
        A36971:
            tp: 1
            ploidy: 3

## genome
genome:
    hg19:
        /gsc/resources/Homo_sapiens_genomes/hg19a/genome/fasta/hg19a.fa
    hg38:
        /gsc/resources/Homo_sapiens_genomes/hg38_no_alt/genome/fasta/hg38_no_alt.fa
array_positions:
    hg19:
        "resources/snp_arrays/hg19/SNP_array_positions.txt"
    hg38:
        "resources/snp_arrays/hg38/SNP_array_positions.txt"
annotation:
    hg19:
        /gsc/resources/annotation/Homo_sapiens.GRCh37.87.gtf
    hg38:
        /gsc/resources/annotation/Homo_sapiens.GRCh38.100.gtf

## Sequence type
sequence_type_defaults:
    ont:
        maxd: 500
        qual: 10
    short:
        maxd: 1000
        qual: 50


# make_windows.py threshold
#   Troubleshoot threshold for single blob/peak, either the case has no CNVs or the data is too noisy at that depth level.
#   If you're sure there are CNVs in the data,  adjust the threshold.
#
#   The size of the bins depends on the germline coverage.
#   The 100000 is the threshold for normal depth to create variable-width bins.
#   Ploidetect was developed for 40x normal, 80x tumor genomes.
#   If the ratio of tumor to normal is not 2:1, adjust the threshold accordingly. So for 40x/40x you might decide to use a larger threshold of 200000 to account for the tumor genome having more noise.
window_threshold: 100000
