### Genome version considerations

# genome_name should match bams
genome_name: "hg19"

# Are we using custom cytobands? put "none" to disable cytoband filtering (not recommended)
cyto_path: auto

# ploidetect_ver should be a branch or tag.  Overriden by ploidetect_local_clone.
ploidetect_ver: v1.4.2

# Leave ploidetect_local_clone blank or 'None' to download from github
ploidetect_local_clone:

# sequence type - "short" for BGI/illumina and "ont" for nanopore
sequence_type: "short"

# Reference data.  Selected by 'genome_name' value.
# TODO: standard config should not refer to GSC - sync w/ gsc_build_config.py

### Defaults that can be left alone safely

output_dir: "ploidetect_out"
temp_dir:
