# A test example of bam setup
bams:
    COLO829_mini_test:
        somatic:
            hartwigT: resources/test_bams/COLO829T.bam
        normal:
            hartwigR: resources/test_bams/COLO829R.bam
